name: havana
favicon: null
layout_spectrum: 0.34237991855479777
typography_spectrum: 0.14661342091858387
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.40841094590723515
  lightness: 0.5191929889842868
  saturation: 0.9331273015122861
  rhythmicContrast: 0.3095534367021173
purpose: []
